%include "headers.inc"


section .data
    head dq 0x00
    data dq 0x00

section .text
global ft_list_push_front
extern malloc

ft_list_push_front:
    mov [rel head], rdi
    mov [rel data], rsi
    mov rdi, t_list_size; the <struc_name>_size auto generated by nasm
    call malloc wrt ..plt
    cmp rax, 0x0
    je end_push
    
assign_node_data:
    mov rbx, rax
    add rbx, t_list.data
    mov rcx, [rel data]
    mov [rbx], rcx ;   new_head->data = data;

assign_node_next:
    mov rbx, rax
    add rbx, t_list.next 
    mov rcx, [rel head] 
    mov rcx, [rcx] ; *begin_list
    mov [rbx], rcx ;     new_head->next = *begin_list;


updating_new_head:
    mov r8, [rel head]; the old begin_list **
    mov [r8], rax;     *begin_list = new_head;


end_push:
    ret


; what is bad about this function that it uses registers down there which is confusing for human
; a better version would be to define many variables with representative name
; but this better version is less effecient so we will stick to the bad version