%include "headers.inc"

section .data
    head dq 0x00
    data dq 0x00

section .text
global ft_list_push_front
extern malloc

ft_list_push_front:
    xor rax, rax
    mov [rel head], rdi
    mov [rel data], rsi
    mov rdi, t_list_size; the <struc_name>_size auto generated by nasm
    call malloc wrt ..plt
    cmp rax, 0x0
    je end_push
    
; debug this part with gdb really slowly
; assign_node_data:
;     mov rbx, [rax + t_list.data]
;     mov rcx, data
;     mov [rbx], rc

; assign_node_next:
;     mov rbx, [rax + t_list.next]
;     mov rcx, [rel head]
;     mov [rcx], rbx

; updating_new_head:
;     mov rbx, [rax]
;     mov rcx, [rel head]
;     mov [rbx], rcx




end_push:
    ret
